import { Activity, Sparkles, Target } from 'lucide-react';
import { Card, CardHeader, CardContent } from '../components/ui/Card';

const PagePlaceholder = ({ title, icon: Icon, description }: { title: string, icon: any, description: string }) => (
  <div className="max-w-6xl mx-auto space-y-10 py-6">
    <div>
      <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
      <p className="text-white/40 text-sm mt-1">{description}</p>
    </div>
    
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      {[1, 2, 3].map(i => (
        <Card key={i} hover>
          <CardHeader>
            <div className="flex items-center gap-2">
              <Icon className="w-4 h-4 text-white/40" />
              <span className="text-xs font-bold uppercase tracking-widest">{title} Module {i}</span>
            </div>
          </CardHeader>
          <CardContent>
            <div className="h-40 bg-white/2 rounded flex items-center justify-center border border-dashed border-border-subtle">
              <p className="text-[10px] text-white/20 uppercase font-bold">Data visualization loading...</p>
            </div>
          </CardContent>
        </Card>
      ))}
    </div>
  </div>
);

export const Performance = () => (
  <PagePlaceholder 
    title="Performance Analytics" 
    icon={Activity} 
    description="Deep dive into your physiological telemetry and power output."
  />
);

export const AITraining = () => (
  <PagePlaceholder 
    title="AI Neural Training" 
    icon={Sparkles} 
    description="Customized training protocols generated by the AESTHER engine."
  />
);

export const Goals = () => (
  <PagePlaceholder 
    title="Target Objectives" 
    icon={Target} 
    description="Define and track your physical and metabolic transformation goals."
  />
);
